name: push-to-docker-registry

on:
  schedule:
    # Once a day, when doesn't matter, let's be nice and not do it at 00:00 like everybody else does.
    - cron: '33 3 * * *'
  push:
    branches: [ master ]

jobs:
  update-base-image-and-push-to-docker-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: update_base_image_build_and_push_containers
        run: PUSH_TO_REGISTRY=1 ./build.sh
