name: verify

on:
  pull_request:
    branches: [ master ]

jobs:
  verify-by-building-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update_base_image_and_build_containers
        run: PUSH_TO_REGISTRY=0 ./build.sh
